# Verify if the PR meets all the requirements for merging on PR review event.

name: PR Pre-merge Check

on:
  pull_request:
    types: [edited]
  pull_request_review:
    types: [submitted]

jobs:
  validate_PR:

    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Validate if the PR is ready to be merged.
        run: echo "Ready!"
        if: ${{ contains(github.payload.pull_request.body, '[ ]') && (github.payload.pull_request.state == "APPROVED") }}
