# Run the mininum required tests for pull requests.

name: Helix PR CI
on:
  pull_request:
    branches: [ master ]

jobs:
  pull_request_CI:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Changed Files
      run: git diff master --name-only > diff.out
    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip.exec=true
    - name: Test metrics-common
      run: cd metrics-common; mvn -q test
      if: ${{ contains(diff.out, 'metrics-common') && (success() || failure()) }}
    - name: Test metadata-store-directory-common
      run: cd metadata-store-directory-common; mvn -q test
      if: ${{ contains(diff.out, 'metadata-store-directory-common') && (success() || failure()) }}
    - name: Test zookeeper-api
      run: cd zookeeper-api; mvn -q test
      if: ${{ contains(diff.out, 'zookeeper-api') && (success() || failure()) }}
    - name: Test helix-common
      run: cd helix-common; mvn -q test
      if: ${{ contains(diff.out, 'helix-common') && (success() || failure()) }}
    - name: Test helix-lock
      run: cd helix-lock; mvn -q test
      if: ${{ contains(diff.out, 'helix-lock') && (success() || failure()) }}
    - name: Test helix-rest
      run: cd helix-rest; mvn -q test
      if: ${{ contains(diff.out, 'helix-rest') && (success() || failure()) }}
    - name: Test helix-core
      run: cd helix-core; mvn -q test
      if: ${{ contains(diff.out, 'helix-core') && (success() || failure()) }}
