# Run the mininum required tests for pull requests.

name: Helix PR CI
on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Get Diff files
      id: file-diff
      run: git diff --name-only ${{ github.base_ref }}..${{ github.head_ref }} -- helix
    - name: Test metrics-common
      run: cat ${{ steps.file-diff.outputs }}
